dist: xenial

language: python
os: osx

python:
  - "3.5"
  - "3.6"
  - "pypy3.5"

#before_install:
  #- sudo apt install ocl-icd-opencl-dev
  #- sudo add-apt-repository ppa:anbe/opencl -y
  #- sudo apt-get update -q
  #- sudo apt-get install pocl -y

install:
  - pip install --editable .
  - pip install coveralls

script: coverage run --source codecad setup.py test

after_success: coveralls
