dist: xenial

language: python

python:
  - "3.5"
  - "3.6"
  - "pypy3.5"

before_install:
  - sudo add-apt-repository -y ppa:anbe/opencl
  - sudo apt-get update -q
  - sudo apt-get install -y pocl-opencl-icd libpocl2 libpocl2-common

install:
  - pip install pybind11 # Must be installed in advance for pyopencl
  - pip install --editable .
  - pip install coveralls

script: coverage run --source codecad setup.py test

after_success: coveralls
