dist: xenial

language: python

python:
  - "3.5"
  - "3.6"
  - "pypy3"

addons:
  apt:
    sources:
      sourceline: 'ppa:anbe/opencl'
    packages:
    - pocl

install:
  - pip install --editable .
  - pip install coveralls

script: coverage run --source codecad setup.py test

after_success: coveralls
