dist: xenial

language: python

python:
  - "3.5"
  - "nightly"
  - "pypy3.5"

before_install:
  - sudo add-apt-repository -y ppa:anbe/opencl
  - sudo apt-get update -q
  - sudo apt-get install ocl-icd-opencl-dev
  - sudo apt-get install -y pocl-opencl-icd libpocl-dev libpocl2 libpocl2-common

install:
  - pip install --user pybind11 # Must be installed in advance for pyopencl
  - pip install --user --editable .
  - pip install --user coveralls

script: coverage run --source codecad setup.py test

after_success: coveralls
